on:
  push:
    branches:
      - master
name: CD
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: pablokbs/hola-docker:${{ github.sha }}

  deploy-to-server:
    name: deploy to server
    runs-on: ubuntu-latest
    needs: docker
    steps:
    -
       name: checkout
       uses: actions/checkout@v3
    -
       name: copy files to target server via scp
       uses: appleboy/scp-action@v0.1.7
       with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: 22
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose.override.yaml"
        target: "/root/"
    -
      name: deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd /root
          sed -i 's/COMMIT_SHA/${{ github.sha }}/g' docker-compose.override.yaml
          docker-compose up -d
